# Generated by Django 4.1.3 on 2022-11-06 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OptionA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Road", "Road"), ("City", "City")],
                        default="City",
                        max_length=16,
                    ),
                ),
                ("choice", models.TextField()),
                ("outcome", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="OptionB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Road", "Road"), ("City", "City")],
                        default="City",
                        max_length=16,
                    ),
                ),
                ("choice", models.TextField()),
                ("outcome", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="RoadEvents",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("image_url", models.URLField()),
                ("verified", models.BooleanField(default=False)),
                (
                    "optionA",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gloomapp.optiona",
                    ),
                ),
                (
                    "optionB",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gloomapp.optionb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CityEvents",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("image_url", models.URLField()),
                ("verified", models.BooleanField(default=False)),
                (
                    "optionA",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gloomapp.optiona",
                    ),
                ),
                (
                    "optionB",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gloomapp.optionb",
                    ),
                ),
            ],
        ),
    ]
