# Generated by Django 4.1.3 on 2022-11-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityEvents",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("optionA", models.JSONField()),
                ("optionB", models.JSONField()),
                ("image_url", models.URLField()),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RoadEvents",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("optionA", models.JSONField()),
                ("optionB", models.JSONField()),
                ("image_url", models.URLField()),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
    ]
