# Generated by Django 4.1.3 on 2022-11-06 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gloomhaven", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.TextField()),
                ("outcome", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="OptionB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.TextField()),
                ("outcome", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="cityevents",
            name="optionA",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gloomhaven.optiona",
            ),
        ),
        migrations.AlterField(
            model_name="cityevents",
            name="optionB",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gloomhaven.optionb",
            ),
        ),
    ]
