# Generated by Django 4.1.3 on 2022-11-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gloomhaven", "0002_optiona_optionb_alter_cityevents_optiona_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiona",
            name="type",
            field=models.CharField(
                choices=[("Road", "Road"), ("City", "City")],
                default="City",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="optionb",
            name="type",
            field=models.CharField(
                choices=[("Road", "Road"), ("City", "City")],
                default="City",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="roadevents",
            name="optionA",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gloomhaven.optiona",
            ),
        ),
        migrations.AlterField(
            model_name="roadevents",
            name="optionB",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gloomhaven.optionb",
            ),
        ),
    ]
